title: "Ways of Working"
author: "Nathan Begbie"
description: "A site to give Praekelt Foundation interns a helpful start"
#subheading: "Really cool blog about ... something"
more: "read more"
url: "http://nathanbegbie.io/wow"
baseurl: "/wow" # comment out if in root directory

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/universalcore/"

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
